import React, { useState, useEffect } from "react";
import { Header } from "./components/Header";
import { IncidentForm } from "./components/IncidentForm";
import { ReportViewer } from "./components/ReportViewer";
import { IncidentHistory } from "./components/IncidentHistory";
import { TicketModal } from "./components/TicketModal";
import { SocDashboard } from "./components/SocDashboard";
import { IncidentTimeline } from "./components/IncidentTimeline";
import { PlaybookPanel } from "./components/PlaybookPanel";
import { ThreatIntelPanel } from "./components/ThreatIntelPanel";
import { EvidenceInsights } from "./components/EvidenceInsights";
import { CaseManagementPanel } from "./components/CaseManagementPanel";
import { AuthPanel } from "./components/AuthPanel";
import { IncidentInput, IncidentAnalysisRecord, TimelineEvent, StructuredIncidentAnalysis, ExtractedIOC } from "./types";
import { parseMarkdownReport } from "./lib/parser";
import { structuredAnalysisToMarkdown, structuredAnalysisToParsedData } from "./lib/structuredReport";
import { evidenceIocs, evidenceTimelineEvents } from "./lib/evidence";
import { clearLocalHistory, loadCloudHistory, loadLocalHistory, saveLocalHistory, upsertCloudRecord, deleteCloudHistory } from "./lib/caseStorage";
import { isSupabaseConfigured, supabase, type User } from "./lib/supabase";
import { ShieldAlert, AlertCircle } from "lucide-react";

function calculateRiskScore(record: Omit<IncidentAnalysisRecord, "riskScore">) { const c:Record<string,number>={Crítica:35,Alta:28,Média:18,Baixa:10}; const l:Record<string,number>={Confirmada:20,Alta:16,Média:10,Baixa:5}; return Math.min(100,(c[record.input.criticidade]||10)+(c[record.parsedData.severity]||18)+(l[record.parsedData.likelihood]||10)+Math.min(record.parsedData.iocs.length*2,10)); }
function calculateConfidenceScore(record: Omit<IncidentAnalysisRecord,"confidenceScore">){let score=record.analysisFormat==="structured-json"?35:20;const likelihood=record.parsedData.likelihood.toLowerCase();if(likelihood.includes("confirm"))score+=25;else if(likelihood.includes("alta"))score+=18;else if(likelihood.includes("média")||likelihood.includes("media"))score+=10;else score+=5;score+=Math.min(record.parsedData.iocs.filter(i=>i.validFormat!==false).length*3,18);score+=Math.min((record.input.evidence?.length||0)*5,15);score+=Math.min(record.parsedData.mitreTechniques.filter(t=>t.validated).length*2,7);return Math.max(0,Math.min(score,100));}
function normalizeRecord(record:IncidentAnalysisRecord):IncidentAnalysisRecord{const normalized:IncidentAnalysisRecord={...record,status:record.status||"Novo",actions:record.actions||record.parsedData.immediateActions,analysisFormat:record.analysisFormat||"legacy-markdown",timeline:record.timeline?.length?record.timeline:[{id:`evt-${record.id}-created`,time:record.createdAt,stage:record.status||"Novo",description:"Incidente registrado no SOC Sentinel."}],playbookCompleted:record.playbookCompleted||[],caseManagement:record.caseManagement||{notes:[],audit:[]}};normalized.riskScore=record.riskScore??calculateRiskScore(normalized);normalized.confidenceScore=record.confidenceScore??calculateConfidenceScore(normalized);return normalized;}
function getErrorMessage(value:unknown,fallback="Não foi possível concluir a análise do incidente."):string{if(!value)return fallback;if(typeof value==="string")return value;if(value instanceof Error)return value.message||fallback;if(typeof value==="object"){const obj=value as Record<string,unknown>;for(const key of ["error","message","detail","details"]){const candidate=obj[key];if(typeof candidate==="string"&&candidate.trim())return candidate;if(candidate&&typeof candidate==="object"){const nested=getErrorMessage(candidate,"");if(nested)return nested;}}try{return JSON.stringify(value);}catch{return fallback;}}return String(value);}
async function parseApiResponse(response:Response){const contentType=response.headers.get("content-type")||"";const rawBody=await response.text();if(!rawBody.trim())return{data:null as any,parseError:"O servidor retornou uma resposta vazia."};if(!contentType.includes("application/json")){const preview=rawBody.replace(/\s+/g," ").slice(0,180);return{data:null as any,parseError:response.ok?"O servidor retornou uma resposta em formato inesperado.":`O servidor retornou um erro não-JSON (${response.status}). ${preview}`};}try{return{data:JSON.parse(rawBody),parseError:null as string|null};}catch{return{data:null as any,parseError:"O servidor retornou JSON inválido. Recarregue a aplicação e tente novamente."};}}
function makeTimelineEvent(stage:string,description:string):TimelineEvent{return{id:`evt-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,time:new Date().toISOString(),stage,description};}
function isStructuredAnalysis(value:unknown):value is StructuredIncidentAnalysis{if(!value||typeof value!=="object")return false;const a=value as Record<string,any>;return Boolean(typeof a.summary==="string"&&a.classification&&typeof a.classification.category==="string"&&Array.isArray(a.iocs)&&Array.isArray(a.immediateActions)&&Array.isArray(a.mitre)&&a.priority&&typeof a.priority.level==="string");}
function mergeIocs(primary:ExtractedIOC[],extra:ExtractedIOC[]){const map=new Map<string,ExtractedIOC>();for(const ioc of [...extra,...primary]){const key=`${ioc.type}:${ioc.value.toLowerCase()}`;const current=map.get(key);if(!current||current.source!=="Evidence Upload")map.set(key,ioc);}return Array.from(map.values());}
function stripEvidenceContent(input:IncidentInput):IncidentInput{if(!input.evidence)return input;return{...input,evidence:input.evidence.map(item=>({...item,content:""}))};}
function mergeRecords(...groups:IncidentAnalysisRecord[][]){const map=new Map<string,IncidentAnalysisRecord>();for(const record of groups.flat())map.set(record.id,normalizeRecord(record));return [...map.values()].sort((a,b)=>b.createdAt.localeCompare(a.createdAt));}

export default function App(){
 const[history,setHistory]=useState<IncidentAnalysisRecord[]>([]);const[activeRecord,setActiveRecord]=useState<IncidentAnalysisRecord|null>(null);const[user,setUser]=useState<User|null>(null);const[isLoading,setIsLoading]=useState(false);const[error,setError]=useState<string|null>(null);const[showHistoryModal,setShowHistoryModal]=useState(false);const[showTicketModal,setShowTicketModal]=useState(false);
 const scope=user?.id||"local";

 useEffect(()=>{setHistory(loadLocalHistory("local").map(normalizeRecord));if(!supabase)return;supabase.auth.getUser().then(({data})=>setUser(data.user||null));const{data:listener}=supabase.auth.onAuthStateChange((_event,session)=>setUser(session?.user||null));return()=>listener.subscription.unsubscribe();},[]);

 useEffect(()=>{let cancelled=false;const sync=async()=>{if(!user){const local=loadLocalHistory("local").map(normalizeRecord);if(!cancelled){setHistory(local);setActiveRecord(null);}return;}try{const cached=loadLocalHistory(user.id).map(normalizeRecord);const cloud=(await loadCloudHistory(user.id)).map(normalizeRecord);const merged=mergeRecords(cloud,cached);saveLocalHistory(merged,user.id);if(!cancelled){setHistory(merged);setActiveRecord(null);}await Promise.all(cached.filter(local=>!cloud.some(remote=>remote.id===local.id)).map(record=>upsertCloudRecord(user.id,record)));}catch(e){console.error("Cloud sync failed",e);if(!cancelled)setError("Falha ao sincronizar os casos com o banco. O cache local continua disponível.");}};sync();return()=>{cancelled=true;};},[user?.id]);

 const saveRecordToHistory=(record:IncidentAnalysisRecord)=>{setHistory(current=>{const updated=[record,...current.filter(h=>h.id!==record.id)];try{saveLocalHistory(updated,scope);}catch(e){console.error("Failed to save local history",e);}return updated;});if(user)upsertCloudRecord(user.id,record).catch(e=>{console.error("Failed to save cloud record",e);setError("O caso foi salvo localmente, mas a sincronização em nuvem falhou.");});};
 const updateActiveRecord=(updatedRecord:IncidentAnalysisRecord)=>{const previous=activeRecord;let nextRecord=updatedRecord;if(previous&&previous.id===updatedRecord.id&&previous.status!==updatedRecord.status){const nextStatus=updatedRecord.status||"Novo";const now=new Date().toISOString();nextRecord={...updatedRecord,timeline:[...(updatedRecord.timeline||previous.timeline||[]),makeTimelineEvent(nextStatus,`Status alterado de ${previous.status||"Novo"} para ${nextStatus}.`)],caseManagement:{...(updatedRecord.caseManagement||{notes:[],audit:[]}),notes:updatedRecord.caseManagement?.notes||[],audit:[...(updatedRecord.caseManagement?.audit||[]),{id:`audit-${Date.now()}`,createdAt:now,actor:user?.email||"SOC Analyst",action:"Status alterado",details:`${previous.status||"Novo"} → ${nextStatus}`}]}};}setActiveRecord(nextRecord);saveRecordToHistory(nextRecord);};
 const handleClearHistory=async()=>{setHistory([]);setActiveRecord(null);clearLocalHistory(scope);if(user)try{await deleteCloudHistory(user.id);}catch(e){console.error("Failed to clear cloud history",e);setError("O cache local foi limpo, mas não foi possível remover os casos da nuvem.");}};
 const refreshAuth=async()=>{if(!supabase)return;const{data}=await supabase.auth.getUser();setUser(data.user||null);};
 const handleAnalyzeIncident=async(input:IncidentInput)=>{setIsLoading(true);setError(null);try{const{evidence,...apiInput}=input;const response=await fetch("/api/analyze-incident",{method:"POST",headers:{"Content-Type":"application/json",Accept:"application/json"},body:JSON.stringify(apiInput)});const{data,parseError}=await parseApiResponse(response);if(parseError)throw new Error(parseError);if(!response.ok)throw new Error(getErrorMessage(data,`Erro HTTP ${response.status} ao conectar com o motor de análise SOC.`));const structuredAnalysis=isStructuredAnalysis(data?.analysis)?data.analysis:undefined;const rawMarkdown=structuredAnalysis?(typeof data.report==="string"&&data.report.trim()?data.report:structuredAnalysisToMarkdown(structuredAnalysis)):data?.report;if(typeof rawMarkdown!=="string"||!rawMarkdown.trim())throw new Error(getErrorMessage(data,"A API respondeu sem um relatório válido."));const parsedData=structuredAnalysis?structuredAnalysisToParsedData(structuredAnalysis):parseMarkdownReport(rawMarkdown);parsedData.iocs=mergeIocs(parsedData.iocs,evidenceIocs(evidence||[]));const createdAt=data.timestamp||new Date().toISOString();const storedInput=stripEvidenceContent(input);const baseRecord:IncidentAnalysisRecord={id:`inc-${Date.now()}`,createdAt,input:storedInput,rawMarkdown,parsedData,structuredAnalysis,analysisFormat:structuredAnalysis?"structured-json":"legacy-markdown",status:"Novo",actions:parsedData.immediateActions,timeline:[...evidenceTimelineEvents(evidence||[]),{id:`evt-${Date.now()}-created`,time:createdAt,stage:"Novo",description:evidence?.length?`Incidente analisado com ${evidence.length} evidência(s) anexada(s) e registrado no SOC Sentinel.`:"Incidente analisado e registrado no SOC Sentinel."}].sort((a,b)=>a.time.localeCompare(b.time)),playbookCompleted:[],caseManagement:{notes:[],audit:[{id:`audit-${Date.now()}`,createdAt,actor:user?.email||"SOC Sentinel",action:"Caso criado",details:`Prioridade ${parsedData.priority} • Severidade ${parsedData.severity}`}]}};const record={...baseRecord,riskScore:calculateRiskScore(baseRecord),confidenceScore:calculateConfidenceScore(baseRecord)};setActiveRecord(record);saveRecordToHistory(record);}catch(err:unknown){console.error("Error analyzing incident:",err);setError(getErrorMessage(err));}finally{setIsLoading(false);}};

 return <div className="min-h-screen bg-slate-950 text-slate-100 flex flex-col font-sans selection:bg-cyan-900 selection:text-cyan-100"><Header totalAnalyzed={history.length} onOpenHistory={()=>setShowHistoryModal(true)} onNewIncident={()=>{setActiveRecord(null);setError(null);}}/><main className="flex-1 max-w-7xl w-full mx-auto px-4 sm:px-6 lg:px-8 py-8 space-y-6"><AuthPanel user={user} onAuthChanged={refreshAuth}/>{isSupabaseConfigured&&<div className="text-[10px] font-mono text-slate-600 text-right">Storage: {user?"Supabase + cache por usuário":"localStorage (login disponível)"}</div>}{error&&<div className="bg-red-950/80 border border-red-800 text-red-200 p-4 rounded-xl flex items-start space-x-3 shadow-lg"><AlertCircle className="w-5 h-5 text-red-400 shrink-0 mt-0.5"/><div className="flex-1 text-xs"><strong className="font-bold block text-sm mb-0.5">Aviso:</strong><span>{error}</span></div></div>}{!activeRecord?<><SocDashboard history={history}/><IncidentForm onSubmit={handleAnalyzeIncident} isLoading={isLoading}/></>:<><ReportViewer record={activeRecord} onUpdateRecord={updateActiveRecord} onOpenTicketModal={()=>setShowTicketModal(true)} onNewIncident={()=>setActiveRecord(null)}/><CaseManagementPanel record={activeRecord} onUpdateRecord={updateActiveRecord}/><EvidenceInsights record={activeRecord}/><ThreatIntelPanel record={activeRecord} onUpdateRecord={updateActiveRecord}/><div className="grid grid-cols-1 xl:grid-cols-2 gap-6"><IncidentTimeline record={activeRecord} onUpdateRecord={updateActiveRecord}/><PlaybookPanel record={activeRecord} onUpdateRecord={updateActiveRecord}/></div></>}</main>{showHistoryModal&&<IncidentHistory history={history} onSelectRecord={rec=>{setActiveRecord(rec);setShowHistoryModal(false);}} onClearHistory={handleClearHistory} onClose={()=>setShowHistoryModal(false)}/>} {showTicketModal&&activeRecord&&<TicketModal record={activeRecord} onClose={()=>setShowTicketModal(false)}/>}<footer className="border-t border-slate-900 bg-slate-950 py-6 text-center text-xs text-slate-500 font-mono"><div className="max-w-7xl mx-auto px-4 flex flex-col sm:flex-row items-center justify-between gap-2"><div className="flex items-center space-x-2"><ShieldAlert className="w-4 h-4 text-cyan-500"/><span>SOC Sentinel L2 • AI-Assisted Incident Response & Threat Analysis</span></div><span>IA como apoio à análise • Validação humana recomendada</span></div></footer></div>;
}
